Attribute VB_Name = "x_GFS_Enumerations"
'Перечисление констант фигур ГраФиС
Public Enum indexPers
   ipAC = 1                                    'АЦ
   ipANR = 2                                   'АНР
   ipAL = 3                                    'АЛ
   ipAKP = 4                                   'АКП
   ipASO = 5                                   'АСО
   ipAT = 6                                    'АТ
   ipADU = 7                                   'АДУ
   ipPNS = 8                                   'ПНС
   ipAA = 9                                    'АА
   ipAV = 10                                   'АВ
   ipAKT = 11                                  'АКТ
   ipAP = 12                                   'АП
   ipAGVT = 13                                 'АГВТ
   ipAG = 14                                   'АГ
   ipAGDZS = 15                                'АГДЗС
   ipKS = 16                                   'КС
   ipPozhLab = 17                              'Пожарная лаборатория
   ipASA = 18                                  'АСА
   ipASH = 19                                  'АШ
   ipAR = 20                                   'АР
   ipLestnPalka = 21                           'Лестница-палка
   ipGrebenkaPGenerat = 22                     'Гребенка пеногенераторов (46)
   ipStacRadio = 23                            'Стационарная радиостанция (590)
   ipPoezd = 24                                'Поезд
   ipSamolet = 25                              'Самолет
   ipHydroSamolet = 26                         'Гидросамолет
   ipVertolet = 27                             'Вертолет
   ipMotoPump = 28                             'Мотопомпа
   ipPricep = 29                               'Прицеп
   ipKorabl = 30                               'Корабль
   ipKater = 31                                'Катер
   ipPrispAvto = 32                            'Приспособленный автомобиль
   ipAvtoObschee = 33                          'Автомобиль общее обозначение (Вообще все - не только пожарные)
   ipInjenerAndSpecAvto = 3000                 'Колесные инженерные и специальные машины
   ipMVD = 3001                                'МВД
   ipAmbulance = 3002                          'Скорая помощь
   ipStvolRuch = 34                            'Водяной ручной ствол
   ipStvolRuchPena = 35                        'Пенный ствол
   ipStvolLafVoda = 36                         'Лафетный водяной (Лафетный автомобильный – разновидность с предопределенными свойствами!)
   ipStvolLafPena = 37                         'Лафетный пенный
   ipStvolLafPoroshok = 38                     'Лафетный порошковый ствол
   ipStvolLafVozimiy = 39                      'Возимый лафетный ствол
   ipHydroelevator = 40                        'Гидроэлеватор
   ipPenosmesitelPerenosn = 41                 'Пеносмеситель переносной
   ipRazvetvlenie = 42                         'Разветвление
   ipLestnSturm = 43                           'Штурмовая лестница
   ipLestn3Kol = 44                            '3-х коленная лестница
   ipPenopodemnik = 45                         'Пеноподъемник
   ipGDZSZvenoVozd = 46                        'Звено ГДЗС (ДАСВ)
   ipGDZSPost = 47                             'Пост ГДЗС
   ipKPP = 48                                  'КПП
   ipDimosos = 49                              'Дымосос
   ipPG = 50                                   'ПГ
   ipPW = 51                                   'ПВ
   ipPK = 52                                   'ПК
   ipOtkritiyVodoistochnik = 53                'Открытый водоисточник
   ipPirs = 54                                 'Пирс
   ipKolodec = 55                              'Колодец
   ipBashna = 56                               'Башня
   ipProzhektor = 57                           'Прожектор
   ipNosimoeRadio = 58                         'Носимая радиостанция
   ipAvtoRadio = 59                            'Автомобильная радиостанция
   ipGromkogovoritel = 60                      'Громкоговоритель
   ipTelefon = 61                              'Телефонный аппарат
   ipStab = 62                                 'Штаб
   ipBU = 63                                   'УТП
   ipPloschadPozhara = 64                      'Площадь прямоугольная
'   ipPloschadPozhara = 64                      'Сектор 90
'   ipPloschadPozhara = 64                      'Сектор 180
'   ipPloschadPozhara = 64                      'Сектор 270
'   ipPloschadPozhara = 64                      'Площадь круглая
'   ipPloschadPozhara = 64                      'Площадь неправильной формы
   ipOchag = 70                                'Очаг пожара
   ipZadiml = 71                               'Задымление
   ipKolonka = 72                              'Колонка
   ipMashNaGusenicah = 73                      'Машина на гусеничном ходу
   ipTank = 74                                 'Танк
   ipDistance = 75                             'Расстояние
   ipStvolGas = 76                             'Газовый ствол
   ipStvolPoroshok = 77                        'Порошковый ствол
   ipVeter = 78                                'Ветер
   ipOgradaZhBeton = 79                        'Ж/б ограда
   ipOgradaKamen = 80                          'Каменная ограда
   ipOgradaMetall = 81                         'Металлическая ограда
   ipLestnKletka = 82                          'Лестничная клетка
   ipRNBD = 83                                 'Решающее направление
   ipRasprostran = 84                          'Распространение
   ipZhDPolotno = 85                           'Ж/д полотно
   ipStorm = 86                                'Огненный шторм
   ipOdinPozhar = 87                           'Одиночный пожар
   ipVsasLineWithSetk = 88                     'Всасывающая линия с сеткой
   ipPodpisPloschadPozhara = 89                'Подпись площадь
   ipGDZSZvenoKisl = 90                        'Звено ГДЗС (ДАСК)
   ipRosaVetrov = 91                           'Роза ветров (76)
   ipPostradavshie = 92                        'Пострадавшие (77)
   ipObrushenie = 93                           'Обрушение
   ipLestnVneshnaya = 94                       'Внешняя лестница
   ipExplikacString = 95                       'Строка экспликации
   ipExplikacYacheyka = 96                     'Ячейка экспликации
   ipRukavLineNapor = 100                      'Напорная линия
   ipRukavLineVsas = 101                       'Всасывающая линия
   ipSvisch = 102                              'Свищ
   ipRukavMost = 103                           'Рукавный мостик
   ipRUPT = 104                                'Ранцевая установка пожаротушения
   ipVodosbornik = 105                         'Водосборник
   ipManometer = 106                           'Манометр
   ipKollector = 107                           'Коллектор
   ipSkatka = 110                              'Скатка
   ipGarmoshka = 111                           'Гармошка
   ipSvodniyGrafik = 120                       'Сводный график
   ipOtcheti = 121                             'Отчеты
   ipSvodniyGrafikNew = 122                    'Сводный график новый
   ipSvodniyGrafikGorenia = 123                'График площади горения
   ipSvodniyGrafikTushenia = 124               'График площади тушения
   ipSvodniyGrafikRashod = 125                 'График расхода
   ipSvodniyGrafikEffectivRashod = 126         'График эффективного расхода
   ipSvodniyGrafikPozhar = 127                 'График площади пожара
   ipSvodniyGrafikUkazatel = 128               'Указатель
   ipSvodniyGrafikVeha = 129                   'Веха
   ipDoroga = 130                              'Дорога
   ipDoroga2 = 131                             'Проезжая часть (Дорога 2)
   ipZdanie = 135                              'Здание
   ipRadialDiagram = 140                       'Радиальная диаграмма
   ipPodpisRukava = 150                        'Подпись диаметра рукава
   ipPodpisPolozhenia = 151                    'Подпись положения
   ipPodpisUniversal = 152                     'Универсальная подпись
   ipPodpisStepenOgnestoykosty = 153           'Подпись степени огнестойкости
   ipPodpisVhodVZdanie = 154                   'Подпись входа в здание
   ipPAObscheeOboznachenie = 160               'ПА – общее обозначение
   ipACL = 161                                 'АЦЛ
   ipACKP = 162                                'АЦКП
   ipAPP = 163                                 'АПП
   ipDerevaniyZabor = 180                      'Деревянный забор
   ipEmkost = 190                              'Емкость
   ipPennayaVstavka = 191                      'Пенная вставка
   ipZazemlenie = 192                          'Заземление
   ipOgnetushitel = 193                        'Огнетушитель
   ipKolichestvo = 195                         'Количество элементов
   ipZakrVodoistochnik = 240                   'Закрытый водоисточник
   ipStenaNesuchayaProstaya = 250              'Стена несущая простая
   ipStenaNesuchayaDvuhsloynaya = 251          'Стена несущая двухслойная
   ipLift = 255                                'Лифт
   ipPech = 256                                'Печь
   ipVent = 257                                'Вентиляция
   ipObriv = 300                               'Обрыв
   ipRov = 301                                 'Ров (канава)
   ipNasip = 302                               'Насыпь (обвалование)
   ipTramWay = 303                             'Трамвайные пути
   ipOpashka = 304                             'Опашка
   ipGranicaRazrusheniy = 305                  'Граница зоны возможных разрушений
   ipGranicaBezopasnoyZoni = 306               'Граница зоны безопасного удаления
   ipRVS = 330                                 'РВС
   ipVzriv = 340                               'Место взрыва
'   ipMashiniMVD = 3001                         'Машины МВД
'   ipMashiniMinzdrav = 3002                    'Машины Минздрав
   ipFormula = 500                             'Формулы
   ipFormulaConnector = 501                    'Соединитель формул
   ipInfoMain = 600                            'Инфоблок Основные сведения
   ipInfoOrganization = 601                    'Инфоблок Организация
   ipInfoObject = 602                          'Инфоблок Объект пожара
   ipInfoCaller = 603                          'Инфоблок Заявитель
   ipInfoSituation = 604                       'Инфоблок Обстановка
   ipInfoOther = 605                           'Инфоблок Прочее
   ipInfoEffects = 606                         'Инфоблок Последствия
   ipInfoSignatures = 607                      'Инфоблок Подписи
   ipInfoCommonFireInfo = 608                  'Инфоблок Сведения о тушении пожара
End Enum

'Перечисления констант объектов железной дороги
Public Enum IndexPersZhD
   ipzVagonPlatforma = 1                       'Вагон – Платформа
   ipzVagonPoluvagon = 2                       'Вагон – Полувагон
   ipzVagonKritiyVagon = 3                     'Вагон – Крытый вагон
   ipzVagonHopper = 4                          'Вагон – Хоппер
   ipzVagonCisterna = 5                        'Вагон – Цистерна
   ipzVagonPost = 6                            'Вагон – Почтовый
   ipzVagonPassenger = 7                       'Вагон – Пассажирский
   ipzVagonElektroGolov = 8                    'Вагон – Электричка головной
   ipzVagonElectroPromezhut = 9                'Вагон – Электричка промежуточный
   ipzTeplovos = 10                            'Тепловоз
   ipzElectrovos = 11                          'Электровоз
   ipzVagonMetroGolov = 12                     'Вагон метро головной
   ipzVagonMetroPromezhut = 13                 'Вагон метро промежуточный
End Enum

'Перечисления констант эвакуационных путей
Public Enum IndexPersEvac
   ipeEvacPutEtazh = 1                         'Эвакуационный путь (по этажу)
   ipeEvacPutDown = 2                          'Эвакуационный путь (вниз)
   ipeEvacVihod = 3                            'Эвакуационный выход
   ipeOgnetushitel = 4                         'Огнетушитель
   ipePozhKran = 5                             'Пожарный кран
   ipeTelefon = 6                              'Телефон
   ipeIzveschatel = 7                          'Извещатель
   ipeApteka = 8                               'Аптечка
   ipePozhLestnica = 9                         'Пожарная лестница
   ipeKolichLudey = 10                         'Кол-во людей
End Enum
